use serde::Deserialize;
use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;

/// キャラクターエントリを表す。
#[derive(Deserialize, Debug)]
struct HeroEntry {
    image: String,
    name: String,
}

/// スキルエントリを表す。
#[derive(Deserialize)]
struct SkillEntry {
    image: String,
    id: u32,
    skill_type: String,
    name: String,
    description: String,
    effects: Vec<String>,
}

/// エフェクト配列を Rust リテラルに変換する。
fn effects_literal(effects: &[String]) -> String {
    let items: Vec<String> = effects
        .iter()
        .map(|effect| format!("\"{}\"", effect.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect();
    format!("&[{}]", items.join(", "))
}

/// レベル番号を取得する。
fn level_number(key: &str) -> u32 {
    key.strip_prefix("level")
        .and_then(|n| n.parse().ok())
        .unwrap_or_else(|| panic!("invalid level key: {key}"))
}

/// 画像パスを生成する。
fn include_image_path(image: &str) -> String {
    if image.starts_with("assets/") {
        format!("concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{image}\")")
    } else {
        panic!("image path must start with 'assets/': {image}")
    }
}

/// Windows 向け exe アイコンとメタデータを埋め込む。
fn embed_windows_resources(manifest_dir: &Path, out_dir: &Path) {
    if env::var("CARGO_CFG_TARGET_OS").ok().as_deref() != Some("windows") {
        return;
    }

    let png_path = manifest_dir.join("assets/icon.png");
    println!("cargo:rerun-if-changed={}", png_path.display());

    let ico_path = out_dir.join("app.ico");
    write_ico_from_png(&png_path, &ico_path);

    winresource::WindowsResource::new()
        .set_icon(ico_path.to_str().expect("invalid ico path"))
        .compile()
        .expect("failed to compile Windows resources");
}

/// PNG から Windows 用 ICO を生成する。
fn write_ico_from_png(png_path: &Path, ico_path: &Path) {
    let image = image::open(png_path).expect("failed to open assets/icon.png");
    let mut icon_dir = ico::IconDir::new(ico::ResourceType::Icon);

    for size in [256, 128, 64, 48, 32, 16] {
        let rgba = image
            .resize_exact(size, size, image::imageops::FilterType::Lanczos3)
            .to_rgba8();
        let icon_image = ico::IconImage::from_rgba_data(size, size, rgba.into_raw());
        let entry = ico::IconDirEntry::encode_as_png(&icon_image).expect("failed to encode icon");
        icon_dir.add_entry(entry);
    }

    let file = fs::File::create(ico_path).expect("failed to create ico file");
    icon_dir.write(file).expect("failed to write ico file");
}

/// メイン関数
fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_path = Path::new(&manifest_dir);
    let heros_dir = manifest_path.join("assets/heros");
    let skills_dir = manifest_path.join("assets/skills");
    let out_dir = env::var("OUT_DIR").unwrap();

    // Windows 向け exe アイコンとメタデータを埋め込む。
    embed_windows_resources(manifest_path, Path::new(&out_dir));

    // キャラクター用画像を生成する。
    println!("cargo:rerun-if-changed={}", heros_dir.display());
    generate_heros_generated(&heros_dir, &out_dir);

    // スキル用画像を生成する。
    println!("cargo:rerun-if-changed={}", skills_dir.display());
    generate_skills_generated(&skills_dir, &out_dir);
}

/// キャラクター一覧を生成する。
/// # Arguments
/// * `heros_dir` - キャラクターディレクトリのパス
/// * `out_dir` - 出力ディレクトリのパス
fn generate_heros_generated(heros_dir: &Path, out_dir: &String) {
    let mut hero_names = Vec::new();

    for entry in fs::read_dir(&heros_dir).expect("failed to read assets/heros") {
        let entry = entry.expect("failed to read directory entry");
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("json") {
            continue;
        }

        println!("cargo:rerun-if-changed={}", path.display());

        let hero_name = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("invalid hero json filename")
            .to_string();
        hero_names.push(hero_name);
    }

    hero_names.sort();
    // println!("cargo:warning=hero_names: {:?}", hero_names);

    let mut output = String::from("// @generated by build.rs — do not edit\n\n");
    output.push_str("use crate::hero::data::HeroData;\n\n");

    for hero_name in &hero_names {
        let path = heros_dir.join(format!("{hero_name}.json"));
        let content = fs::read_to_string(&path).expect("failed to read hero json");
        let heros: Vec<HeroEntry> = serde_json::from_str(&content).expect("failed to parse hero json");

        // println!("cargo:warning=heros: {:?}", heros);

        output.push_str(&format!("#[allow(dead_code)]\npub mod {hero_name} {{\n"));
        output.push_str("use super::HeroData;\n\n");

        let mut row_names = Vec::new();

        for (row_index, hero) in heros.iter().enumerate() {
            let row_name = format!("ROW_{row_index}");
            row_names.push(row_name.clone());

            output.push_str(&format!("const {row_name}: HeroData = "));

            output.push_str(&format!(
                "HeroData::new(\negui::include_image!({}),\n\"{}\",\n);\n",
                include_image_path(&hero.image),
                hero.name.replace('\\', "\\\\").replace('"', "\\\""),
            ));

            output.push_str("\n\n");
        }

        output.push_str("pub const HERO_DATA: &[HeroData] = &[\n");
        for row_name in &row_names {
            output.push_str(&format!("{row_name},\n"));
        }
        output.push_str("];\n");
        output.push_str("}\n");
    }

    // println!("cargo:warning=output: {:?}", output);

    let out_path = Path::new(&out_dir).join("heros_generated.rs");
    fs::write(&out_path, output).expect("failed to write generated heros");
}

/// スキル一覧を生成する。
/// # Arguments
/// * `skills_dir` - スキルディレクトリのパス
/// * `out_dir` - 出力ディレクトリのパス
fn generate_skills_generated(skills_dir: &Path, out_dir: &String) {
    let mut hero_names = Vec::new();

    for entry in fs::read_dir(&skills_dir).expect("failed to read assets/skills") {
        let entry = entry.expect("failed to read directory entry");
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("json") {
            continue;
        }

        println!("cargo:rerun-if-changed={}", path.display());

        let hero_name = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("invalid skill json filename")
            .to_string();
        hero_names.push(hero_name);
    }

    hero_names.sort();

    let mut output = String::from("// @generated by build.rs — do not edit\n\n");
    output.push_str("use crate::hero::data::SkillData;\n\n");

    for hero_name in &hero_names {
        let path = skills_dir.join(format!("{hero_name}.json"));
        let content = fs::read_to_string(&path).expect("failed to read skill json");
        let levels: HashMap<String, Vec<SkillEntry>> =
            serde_json::from_str(&content).expect("failed to parse skill json");

        let mut level_keys: Vec<_> = levels.keys().cloned().collect();
        level_keys.sort_by_key(|key| level_number(key));

        output.push_str(&format!("#[allow(dead_code)]\npub mod {hero_name} {{\n"));
        output.push_str("use super::SkillData;\n\n");

        let mut row_names = Vec::new();

        for (row_index, level_key) in level_keys.iter().enumerate() {
            let row_name = format!("ROW_{row_index}");
            row_names.push(row_name.clone());

            output.push_str(&format!("const {row_name}: &[SkillData] = &[\n"));

            for skill in &levels[level_key] {
                output.push_str(&format!(
                    "SkillData::new(\negui::include_image!({}),\n{},\n\"{}\",\n\"{}\",\n\"{}\",\n\"{}\",\n{},\n),\n",
                    include_image_path(&skill.image),
                    skill.id,
                    level_key,
                    skill.skill_type.replace('\\', "\\\\").replace('"', "\\\""),
                    skill.name.replace('\\', "\\\\").replace('"', "\\\""),
                    skill.description.replace('\\', "\\\\").replace('"', "\\\""),
                    effects_literal(&skill.effects),
                ));
            }

            output.push_str("];\n\n");
        }

        output.push_str("pub const SKILL_DATA: &[&[SkillData]] = &[\n");
        for row_name in &row_names {
            output.push_str(&format!("{row_name},\n"));
        }
        output.push_str("];\n");
        output.push_str("}\n");
    }

    // println!("cargo:warning=output: {:?}", output);

    let out_path = Path::new(&out_dir).join("skills_generated.rs");
    fs::write(&out_path, output).expect("failed to write generated skills");
}
